### ISSUE TITLE
avr.pizza is just sending a 502 error

### ISSUE THREAD

**Issue by ghost** [noopkat/avr-pizza#7]
avr-pizza module can't work now.

**Comment by noopkat** [comment]
Hi @focalhot 

Sorry for the downtime! This has been a recurring issue for 🍕 for a while now.
I spent most of today on stability improvements and an infrastructure migration, so things should be working much better now and the service will be more resilient going forwards.

Let me know if you run into any other issues 🙇‍♀️

**Comment by focalhot** [comment]
How to convert .ino file to .hex file without Arduino IDE?
Thanks again. @noopkat
